chore: install xuath and use public bridge for web tests

diff --git a/.github/workflows/e2e_web.yml b/.github/workflows/e2e_web.yml
--- a/.github/workflows/e2e_web.yml
+++ b/.github/workflows/e2e_web.yml
@@ -44,46 +44,46 @@ jobs:
     - name: Setup dependencies
       run: |
         if [ "$(id -u)" -ne 0 ]; then
-          sudo apt-get update && sudo apt-get install --no-install-recommends -y xvfb
+          sudo apt-get update && sudo apt-get install --no-install-recommends -y xvfb xauth
         else
-          apt-get update && apt-get install --no-install-recommends -y xvfb
+          apt-get update && apt-get install --no-install-recommends -y xvfb xauth
         fi
         pnpm install --frozen-lockfile
         pnpm --filter demo-wallet e2e:deps
 
-    - name: Start TON Connect Bridge
-      run: |
-        echo "Starting TON Connect Bridge service with docker-compose.memory.yml..."
-        docker compose -f docker-compose.bridge.yml up -d
-        echo "Waiting for services to be ready..."
-        sleep 2
+    # - name: Start TON Connect Bridge
+    #   run: |
+    #     echo "Starting TON Connect Bridge service with docker-compose.memory.yml..."
+    #     docker compose -f docker-compose.bridge.yml up -d
+    #     echo "Waiting for services to be ready..."
+    #     sleep 2
 
-        echo "Checking if TON Connect Bridge service is accessible..."
-        max_attempts=30
-        attempt=1
+    #     echo "Checking if TON Connect Bridge service is accessible..."
+    #     max_attempts=30
+    #     attempt=1
         
-        while [ $attempt -le $max_attempts ]; do
-          echo "Attempt $attempt/$max_attempts: Checking http://localhost:8081/bridge"
-          if curl -I -f -s -o /dev/null -w "%{http_code}\n" http://localhost:9103/metrics; then
-            echo "✅ TON Connect Bridge service is accessible at http://localhost:8081/bridge"
-            break
-          else
-            echo "❌ TON Connect Bridge service not ready yet, waiting 5 seconds..."
-            sleep 2
-            attempt=$((attempt + 1))
-          fi
-        done
+    #     while [ $attempt -le $max_attempts ]; do
+    #       echo "Attempt $attempt/$max_attempts: Checking http://localhost:8081/bridge"
+    #       if curl -I -f -s -o /dev/null -w "%{http_code}\n" http://localhost:9103/metrics; then
+    #         echo "✅ TON Connect Bridge service is accessible at http://localhost:8081/bridge"
+    #         break
+    #       else
+    #         echo "❌ TON Connect Bridge service not ready yet, waiting 5 seconds..."
+    #         sleep 2
+    #         attempt=$((attempt + 1))
+    #       fi
+    #     done
         
-        if [ $attempt -gt $max_attempts ]; then
-          echo "❌ TON Connect Bridge service failed to start within expected time"
-          echo "Docker containers status:"
-          docker compose -f docker-compose.bridge.yml ps
-          echo "TON Connect Bridge container logs:"
-          docker compose -f docker-compose.bridge.yml logs bridge
-          exit 1
-        fi
+    #     if [ $attempt -gt $max_attempts ]; then
+    #       echo "❌ TON Connect Bridge service failed to start within expected time"
+    #       echo "Docker containers status:"
+    #       docker compose -f docker-compose.bridge.yml ps
+    #       echo "TON Connect Bridge container logs:"
+    #       docker compose -f docker-compose.bridge.yml logs bridge
+    #       exit 1
+    #     fi
         
-        echo "🚀 TON Connect Bridge service is now running and accessible at http://localhost:8081/bridge"
+    #     echo "🚀 TON Connect Bridge service is now running and accessible at http://localhost:8081/bridge"
 
     - name: Run web e2e specs
       run: |
@@ -92,7 +92,8 @@ jobs:
         xvfb-run pnpm e2e
       env:
         WALLET_MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
-        VITE_BRIDGE_URL: 'http://localhost:8081/bridge'
+        # VITE_BRIDGE_URL: 'http://localhost:8081/bridge'
+        VITE_BRIDGE_URL: 'https://connect.ton.org/bridge'
         ALLURE_BASE_URL: ${{ secrets.ALLURE_BASE_URL }}
         ALLURE_API_TOKEN: ${{ secrets.ALLURE_API_TOKEN_CI }}
         ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
